name: "Link IO App"
on:
  push:
    branches:
      - github-actions
jobs:
  link:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install toolbelt
        run: |
          yarn global add vtex
          yarn install
          echo "$(yarn global bin)" >> $GITHUB_PATH
      - uses: vtex/action-toolbelt-login@v1
        with:
          account: ronadev
          app-key: ${{ secrets.APP_KEY }}
          app-token: ${{ secrets.APP_TOKEN }}
      - run: |
          echo "yes" | vtex use actions
          vtex link --no-watch
